[package]
name = "onemoretime"
version = "0.0.0"
description = "A Tauri App"
authors = ["Tokuhiro Matsuno"]
license = "MIT"
repository = "https://github.com/tokuhirom/onemoretime"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = ["shell-open", "system-tray", "config-json5"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0"

log = { version = "0.4.20", features = [] }
simplelog = "0.12.1"

config = { version = "0.13.4", features = [] }
anyhow = "1.0.77"

cocoa = "0.25.0"

confy = "0.5.1"

apple-sys = { version = "0.2.0", features = ["CoreGraphics", "CoreFoundation"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
